#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ExchangeRete.Droid.Resource", IsApplication=true)]

namespace ExchangeRete.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::ExchangeRete.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::ExchangeRete.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::ExchangeRete.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::ExchangeRete.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::ExchangeRete.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::ExchangeRete.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::ExchangeRete.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::ExchangeRete.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::ExchangeRete.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::ExchangeRete.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxBind = global::ExchangeRete.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxDropDownItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxGroupItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxLang = global::ExchangeRete.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxSource = global::ExchangeRete.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvvmCrossTagId = global::ExchangeRete.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvxBindingTagUnique = global::ExchangeRete.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxBind = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxLang = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl = global::ExchangeRete.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl_MvxTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView = global::ExchangeRete.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView = global::ExchangeRete.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView_MvxSource = global::ExchangeRete.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView = global::ExchangeRete.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = global::ExchangeRete.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = global::ExchangeRete.Droid.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::ViewPagerIndicator.Resource.Attribute.vpiTabTextStyle = global::ExchangeRete.Droid.Resource.Attribute.vpiTabTextStyle;
			global::ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = global::ExchangeRete.Droid.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::ViewPagerIndicator.Resource.Attribute.vpi_centered = global::ExchangeRete.Droid.Resource.Attribute.vpi_centered;
			global::ViewPagerIndicator.Resource.Attribute.vpi_clipPadding = global::ExchangeRete.Droid.Resource.Attribute.vpi_clipPadding;
			global::ViewPagerIndicator.Resource.Attribute.vpi_fillColor = global::ExchangeRete.Droid.Resource.Attribute.vpi_fillColor;
			global::ViewPagerIndicator.Resource.Attribute.vpi_footerColor = global::ExchangeRete.Droid.Resource.Attribute.vpi_footerColor;
			global::ViewPagerIndicator.Resource.Attribute.vpi_footerIndicatorHeight = global::ExchangeRete.Droid.Resource.Attribute.vpi_footerIndicatorHeight;
			global::ViewPagerIndicator.Resource.Attribute.vpi_footerIndicatorStyle = global::ExchangeRete.Droid.Resource.Attribute.vpi_footerIndicatorStyle;
			global::ViewPagerIndicator.Resource.Attribute.vpi_footerIndicatorUnderlinePadding = global::ExchangeRete.Droid.Resource.Attribute.vpi_footerIndicatorUnderlinePadding;
			global::ViewPagerIndicator.Resource.Attribute.vpi_footerLineHeight = global::ExchangeRete.Droid.Resource.Attribute.vpi_footerLineHeight;
			global::ViewPagerIndicator.Resource.Attribute.vpi_footerPadding = global::ExchangeRete.Droid.Resource.Attribute.vpi_footerPadding;
			global::ViewPagerIndicator.Resource.Attribute.vpi_orientation = global::ExchangeRete.Droid.Resource.Attribute.vpi_orientation;
			global::ViewPagerIndicator.Resource.Attribute.vpi_pageColor = global::ExchangeRete.Droid.Resource.Attribute.vpi_pageColor;
			global::ViewPagerIndicator.Resource.Attribute.vpi_radius = global::ExchangeRete.Droid.Resource.Attribute.vpi_radius;
			global::ViewPagerIndicator.Resource.Attribute.vpi_selectedBold = global::ExchangeRete.Droid.Resource.Attribute.vpi_selectedBold;
			global::ViewPagerIndicator.Resource.Attribute.vpi_selectedColor = global::ExchangeRete.Droid.Resource.Attribute.vpi_selectedColor;
			global::ViewPagerIndicator.Resource.Attribute.vpi_snap = global::ExchangeRete.Droid.Resource.Attribute.vpi_snap;
			global::ViewPagerIndicator.Resource.Attribute.vpi_strokeColor = global::ExchangeRete.Droid.Resource.Attribute.vpi_strokeColor;
			global::ViewPagerIndicator.Resource.Attribute.vpi_strokeWidth = global::ExchangeRete.Droid.Resource.Attribute.vpi_strokeWidth;
			global::ViewPagerIndicator.Resource.Attribute.vpi_textColor = global::ExchangeRete.Droid.Resource.Attribute.vpi_textColor;
			global::ViewPagerIndicator.Resource.Attribute.vpi_textSize = global::ExchangeRete.Droid.Resource.Attribute.vpi_textSize;
			global::ViewPagerIndicator.Resource.Attribute.vpi_titlePadding = global::ExchangeRete.Droid.Resource.Attribute.vpi_titlePadding;
			global::ViewPagerIndicator.Resource.Attribute.vpi_topPadding = global::ExchangeRete.Droid.Resource.Attribute.vpi_topPadding;
			global::ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = global::ExchangeRete.Droid.Resource.Boolean.default_circle_indicator_centered;
			global::ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = global::ExchangeRete.Droid.Resource.Boolean.default_circle_indicator_snap;
			global::ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = global::ExchangeRete.Droid.Resource.Boolean.default_title_indicator_selected_bold;
			global::ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = global::ExchangeRete.Droid.Resource.Color.default_circle_indicator_fill_color;
			global::ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = global::ExchangeRete.Droid.Resource.Color.default_circle_indicator_page_color;
			global::ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = global::ExchangeRete.Droid.Resource.Color.default_circle_indicator_stroke_color;
			global::ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = global::ExchangeRete.Droid.Resource.Color.default_title_indicator_footer_color;
			global::ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = global::ExchangeRete.Droid.Resource.Color.default_title_indicator_selected_color;
			global::ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = global::ExchangeRete.Droid.Resource.Color.default_title_indicator_text_color;
			global::ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = global::ExchangeRete.Droid.Resource.Color.vpi__background_holo_dark;
			global::ViewPagerIndicator.Resource.Color.vpi__background_holo_light = global::ExchangeRete.Droid.Resource.Color.vpi__background_holo_light;
			global::ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::ExchangeRete.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::ExchangeRete.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = global::ExchangeRete.Droid.Resource.Color.vpi__bright_foreground_holo_dark;
			global::ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = global::ExchangeRete.Droid.Resource.Color.vpi__bright_foreground_holo_light;
			global::ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::ExchangeRete.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::ExchangeRete.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::ViewPagerIndicator.Resource.Color.vpi__dark_theme = global::ExchangeRete.Droid.Resource.Color.vpi__dark_theme;
			global::ViewPagerIndicator.Resource.Color.vpi__light_theme = global::ExchangeRete.Droid.Resource.Color.vpi__light_theme;
			global::ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = global::ExchangeRete.Droid.Resource.Dimension.default_circle_indicator_radius;
			global::ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = global::ExchangeRete.Droid.Resource.Dimension.default_circle_indicator_stroke_width;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_clip_padding;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_footer_line_height;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_footer_padding;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_text_size;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_title_padding;
			global::ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = global::ExchangeRete.Droid.Resource.Dimension.default_title_indicator_top_padding;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator_focused = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator_focused;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator_selected = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator_selected;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator_selected_focused = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator_selected_focused;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator_selected_pressed = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator_selected_pressed;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator_unselected = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator_unselected;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator_unselected_focused = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator_unselected_focused;
			global::ViewPagerIndicator.Resource.Drawable.custom_tab_indicator_unselected_pressed = global::ExchangeRete.Droid.Resource.Drawable.custom_tab_indicator_unselected_pressed;
			global::ViewPagerIndicator.Resource.Drawable.vpi__tab_indicator = global::ExchangeRete.Droid.Resource.Drawable.vpi__tab_indicator;
			global::ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_focused_holo = global::ExchangeRete.Droid.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_holo = global::ExchangeRete.Droid.Resource.Drawable.vpi__tab_selected_holo;
			global::ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_pressed_holo = global::ExchangeRete.Droid.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_focused_holo = global::ExchangeRete.Droid.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_holo = global::ExchangeRete.Droid.Resource.Drawable.vpi__tab_unselected_holo;
			global::ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::ExchangeRete.Droid.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::ViewPagerIndicator.Resource.Id.horizontal = global::ExchangeRete.Droid.Resource.Id.horizontal;
			global::ViewPagerIndicator.Resource.Id.indicator = global::ExchangeRete.Droid.Resource.Id.indicator;
			global::ViewPagerIndicator.Resource.Id.none = global::ExchangeRete.Droid.Resource.Id.none;
			global::ViewPagerIndicator.Resource.Id.pager = global::ExchangeRete.Droid.Resource.Id.pager;
			global::ViewPagerIndicator.Resource.Id.triangle = global::ExchangeRete.Droid.Resource.Id.triangle;
			global::ViewPagerIndicator.Resource.Id.underline = global::ExchangeRete.Droid.Resource.Id.underline;
			global::ViewPagerIndicator.Resource.Id.vertical = global::ExchangeRete.Droid.Resource.Id.vertical;
			global::ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = global::ExchangeRete.Droid.Resource.Integer.default_circle_indicator_orientation;
			global::ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = global::ExchangeRete.Droid.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::ViewPagerIndicator.Resource.Layout.themed_circles = global::ExchangeRete.Droid.Resource.Layout.themed_circles;
			global::ViewPagerIndicator.Resource.Layout.themed_titles = global::ExchangeRete.Droid.Resource.Layout.themed_titles;
			global::ViewPagerIndicator.Resource.Layout.vpi__tab = global::ExchangeRete.Droid.Resource.Layout.vpi__tab;
			global::ViewPagerIndicator.Resource.Style.CustomCirclePageIndicator = global::ExchangeRete.Droid.Resource.Style.CustomCirclePageIndicator;
			global::ViewPagerIndicator.Resource.Style.CustomTabPageIndicator = global::ExchangeRete.Droid.Resource.Style.CustomTabPageIndicator;
			global::ViewPagerIndicator.Resource.Style.CustomTabPageIndicator_Text = global::ExchangeRete.Droid.Resource.Style.CustomTabPageIndicator_Text;
			global::ViewPagerIndicator.Resource.Style.CustomTitlePageIndicator = global::ExchangeRete.Droid.Resource.Style.CustomTitlePageIndicator;
			global::ViewPagerIndicator.Resource.Style.StyledIndicators = global::ExchangeRete.Droid.Resource.Style.StyledIndicators;
			global::ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = global::ExchangeRete.Droid.Resource.Style.TextAppearance_TabPageIndicator;
			global::ViewPagerIndicator.Resource.Style.Theme_PageIndicatorDefaults = global::ExchangeRete.Droid.Resource.Style.Theme_PageIndicatorDefaults;
			global::ViewPagerIndicator.Resource.Style.Widget = global::ExchangeRete.Droid.Resource.Style.Widget;
			global::ViewPagerIndicator.Resource.Style.Widget_CirclePageIndicator = global::ExchangeRete.Droid.Resource.Style.Widget_CirclePageIndicator;
			global::ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator = global::ExchangeRete.Droid.Resource.Style.Widget_TabPageIndicator;
			global::ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator_Text = global::ExchangeRete.Droid.Resource.Style.Widget_TabPageIndicator_Text;
			global::ViewPagerIndicator.Resource.Style.Widget_TitlePageIndicator = global::ExchangeRete.Droid.Resource.Style.Widget_TitlePageIndicator;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_centered = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_centered;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_fillColor = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_fillColor;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_orientation = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_orientation;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_pageColor = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_pageColor;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_radius = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_radius;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_snap = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_snap;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_strokeColor = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_strokeColor;
			global::ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_vpi_strokeWidth = global::ExchangeRete.Droid.Resource.Styleable.CirclePageIndicator_vpi_strokeWidth;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_clipPadding = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_clipPadding;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_footerColor = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_footerColor;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_footerIndicatorHeight = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_footerIndicatorHeight;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_footerIndicatorStyle = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_footerIndicatorStyle;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_footerIndicatorUnderlinePadding = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_footerIndicatorUnderlinePadding;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_footerLineHeight = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_footerLineHeight;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_footerPadding = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_footerPadding;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_selectedBold = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_selectedBold;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_selectedColor = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_selectedColor;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_textColor = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_textColor;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_textSize = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_textSize;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_titlePadding = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_titlePadding;
			global::ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_vpi_topPadding = global::ExchangeRete.Droid.Resource.Styleable.TitlePageIndicator_vpi_topPadding;
			global::ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = global::ExchangeRete.Droid.Resource.Styleable.ViewPagerIndicator;
			global::ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::ExchangeRete.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::ExchangeRete.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabTextStyle = global::ExchangeRete.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabTextStyle;
			global::ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::ExchangeRete.Droid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::MvvmCross.Droid.Support.Core.UI.Resource.String.library_name = global::ExchangeRete.Droid.Resource.String.library_name;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxBind = global::ExchangeRete.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxDropDownItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxGroupItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxItemTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxLang = global::ExchangeRete.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxSource = global::ExchangeRete.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxTemplate = global::ExchangeRete.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Id.MvvmCrossTagId = global::ExchangeRete.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.Fragment.Resource.Id.MvxBindingTagUnique = global::ExchangeRete.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.Fragment.Resource.String.library_name = global::ExchangeRete.Droid.Resource.String.library_name;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding_MvxBind = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding_MvxLang = global::ExchangeRete.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxControl = global::ExchangeRete.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxControl_MvxTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxExpandableListView = global::ExchangeRete.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxImageView = global::ExchangeRete.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxImageView_MvxSource = global::ExchangeRete.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView = global::ExchangeRete.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView_MvxItemTemplate = global::ExchangeRete.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010019
			public const int MvxBind = 2130771993;
			
			// aapt resource value: 0x7f01001d
			public const int MvxDropDownItemTemplate = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int MvxGroupItemTemplate = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int MvxItemTemplate = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public const int MvxLang = 2130771994;
			
			// aapt resource value: 0x7f01001f
			public const int MvxSource = 2130771999;
			
			// aapt resource value: 0x7f01001b
			public const int MvxTemplate = 2130771995;
			
			// aapt resource value: 0x7f010023
			public const int bring_to_clamp = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int clamp = 2130772002;
			
			// aapt resource value: 0x7f010020
			public const int gravity = 2130772000;
			
			// aapt resource value: 0x7f010026
			public const int left_swipe_enabled = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int right_swipe_enabled = 2130772007;
			
			// aapt resource value: 0x7f010021
			public const int sticky = 2130772001;
			
			// aapt resource value: 0x7f010024
			public const int sticky_sensitivity = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int swipe_enabled = 2130772005;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int vpiTabPageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int vpiTabTextStyle = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int vpiTitlePageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int vpi_centered = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int vpi_clipPadding = 2130771980;
			
			// aapt resource value: 0x7f010005
			public const int vpi_fillColor = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int vpi_footerColor = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int vpi_footerIndicatorHeight = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int vpi_footerIndicatorStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int vpi_footerIndicatorUnderlinePadding = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int vpi_footerLineHeight = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int vpi_footerPadding = 2130771986;
			
			// aapt resource value: 0x7f010007
			public const int vpi_orientation = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int vpi_pageColor = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int vpi_radius = 2130771976;
			
			// aapt resource value: 0x7f010014
			public const int vpi_selectedBold = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int vpi_selectedColor = 2130771987;
			
			// aapt resource value: 0x7f010009
			public const int vpi_snap = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int vpi_strokeColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int vpi_strokeWidth = 2130771979;
			
			// aapt resource value: 0x7f010015
			public const int vpi_textColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int vpi_textSize = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int vpi_titlePadding = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int vpi_topPadding = 2130771992;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_centered = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_snap = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int default_title_indicator_selected_bold = 2131230722;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070008
			public const int default_circle_indicator_fill_color = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int default_circle_indicator_page_color = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int default_circle_indicator_stroke_color = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int default_title_indicator_footer_color = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int default_title_indicator_selected_color = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int default_title_indicator_text_color = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int vpi__background_holo_dark = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int vpi__background_holo_light = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int vpi__bright_foreground_disabled_holo_light = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int vpi__bright_foreground_holo_dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int vpi__bright_foreground_holo_light = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int vpi__bright_foreground_inverse_holo_light = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int vpi__dark_theme = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int vpi__light_theme = 2131165199;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0000
			public const int default_circle_indicator_radius = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int default_circle_indicator_stroke_width = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int default_title_indicator_clip_padding = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int default_title_indicator_footer_indicator_height = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int default_title_indicator_footer_indicator_underline_padding = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int default_title_indicator_footer_line_height = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int default_title_indicator_footer_padding = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int default_title_indicator_text_size = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int default_title_indicator_title_padding = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int default_title_indicator_top_padding = 2131361801;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int custom_tab_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int custom_tab_indicator_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int custom_tab_indicator_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int custom_tab_indicator_selected_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int custom_tab_indicator_selected_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int custom_tab_indicator_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int custom_tab_indicator_unselected_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_tab_indicator_unselected_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Ok = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int splash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int vpi__tab_indicator = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int vpi__tab_selected_focused_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int vpi__tab_selected_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int vpi__tab_selected_pressed_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int vpi__tab_unselected_focused_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int vpi__tab_unselected_holo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int vpi__tab_unselected_pressed_holo = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0000
			public const int MvvmCrossTagId = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int MvxBindingTagUnique = 2131427329;
			
			// aapt resource value: 0x7f0b0009
			public const int bankslist = 2131427337;
			
			// aapt resource value: 0x7f0b0008
			public const int button = 2131427336;
			
			// aapt resource value: 0x7f0b0002
			public const int horizontal = 2131427330;
			
			// aapt resource value: 0x7f0b000e
			public const int indicator = 2131427342;
			
			// aapt resource value: 0x7f0b0004
			public const int none = 2131427332;
			
			// aapt resource value: 0x7f0b000d
			public const int pager = 2131427341;
			
			// aapt resource value: 0x7f0b0007
			public const int swipe = 2131427335;
			
			// aapt resource value: 0x7f0b000b
			public const int textView1 = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int textView2 = 2131427338;
			
			// aapt resource value: 0x7f0b0005
			public const int triangle = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int underline = 2131427334;
			
			// aapt resource value: 0x7f0b0003
			public const int vertical = 2131427331;
			
			// aapt resource value: 0x7f0b000c
			public const int viewPager = 2131427340;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_orientation = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_title_indicator_footer_indicator_style = 2131296257;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int banks_list_item = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BanksView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cities_list_item = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CitiesView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SplashScreen = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int TabView = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int themed_circles = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int themed_titles = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int vpi__tab = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int CustomCirclePageIndicator = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CustomTabPageIndicator = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int CustomTabPageIndicator_Text = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int CustomTitlePageIndicator = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int StyledIndicators = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int TextAppearance_TabPageIndicator = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int Theme_PageIndicatorDefaults = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int Theme_Splash = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int Widget = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Widget_CirclePageIndicator = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int Widget_TabPageIndicator = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Widget_TabPageIndicator_Text = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int Widget_TitlePageIndicator = 2131099656;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[]
			{
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_vpi_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_vpi_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_vpi_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_vpi_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_vpi_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_vpi_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_vpi_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_vpi_strokeWidth = 7;
			
			public static int[] MvxBinding = new int[]
			{
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771995};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[]
			{
					2130771998};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771999};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771996,
					2130771997};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SwipeLayout = new int[]
			{
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007};
			
			// aapt resource value: 3
			public const int SwipeLayout_bring_to_clamp = 3;
			
			// aapt resource value: 2
			public const int SwipeLayout_clamp = 2;
			
			// aapt resource value: 0
			public const int SwipeLayout_gravity = 0;
			
			// aapt resource value: 6
			public const int SwipeLayout_left_swipe_enabled = 6;
			
			// aapt resource value: 7
			public const int SwipeLayout_right_swipe_enabled = 7;
			
			// aapt resource value: 1
			public const int SwipeLayout_sticky = 1;
			
			// aapt resource value: 4
			public const int SwipeLayout_sticky_sensitivity = 4;
			
			// aapt resource value: 5
			public const int SwipeLayout_swipe_enabled = 5;
			
			public static int[] TitlePageIndicator = new int[]
			{
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_vpi_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_vpi_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_vpi_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_vpi_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_vpi_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_vpi_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_vpi_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_vpi_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_vpi_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_vpi_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_vpi_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_vpi_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_vpi_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 2;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTabTextStyle = 3;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
